site_name: Certificate Authority Guide
theme: readthedocs
nav:
  - Introduction: index.md
  - Operational Overview and Setup: details_and_setup.md
  - Generating a Certificate Authority: generating_ca.md
  - Distribution: distribution.md
  - Service Certificates: service_certificates.md
  - Revoking Service Certificates: revocation_services.md
  - Revoking the Intermediate CA Certificate: revocation_ca.md
  - References: references.md
